# Generated by Django 5.0.6 on 2024-05-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselPageIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carouselIndex', models.IntegerField()),
                ('path', models.CharField(max_length=300)),
                ('isCurrent', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'CarouselPageIndex',
            },
        ),
    ]
