# Generated by Django 5.0.6 on 2024-05-22 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carouselpageindex',
            old_name='isCurrent',
            new_name='isActive',
        ),
    ]
