# Generated by Django 5.0.6 on 2024-05-22 06:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productiontype_listinguseronline_listingproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingproduct',
            name='product_date_listed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
