# Generated by Django 5.0.6 on 2024-05-22 06:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_listingproduct_product_date_listed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='carouselpageindex',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='listingproduct',
            old_name='product_date_listed',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='listingproduct',
            old_name='product_folder_image',
            new_name='folder_image',
        ),
        migrations.RenameField(
            model_name='listingproduct',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='listingproduct',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='listingproduct',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='listinguseronline',
            name='offlineAt',
        ),
        migrations.RemoveField(
            model_name='listinguseronline',
            name='onlineAt',
        ),
        migrations.AddField(
            model_name='listingproduct',
            name='description',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='listingproduct',
            name='dislike_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listingproduct',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listinguseronline',
            name='offline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listinguseronline',
            name='online_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listinguseronline',
            name='firsttime_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100000)),
                ('comment_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('like_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('comment_user_id', models.ForeignKey(db_column='comment_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment_user_id', to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='shop.listingproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100000)),
                ('comment_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('like_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('productcomment_id', models.ForeignKey(db_column='productcomment_id', on_delete=django.db.models.deletion.CASCADE, related_name='productcomment_id', to='shop.productcomment')),
                ('reply_comment_user_id', models.ForeignKey(db_column='reply_comment_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reply_comment_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
