# Generated by Django 5.0.6 on 2024-05-23 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_productcomment_product_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='like_count',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.IntegerField(default=0)),
                ('rate_star', models.IntegerField(default=0)),
                ('product_type_id', models.ForeignKey(db_column='product_id_like', on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_id_like', to='shop.productiontype')),
                ('user_like_id', models.ForeignKey(db_column='user_like_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_like_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
