# Generated by Django 5.0.6 on 2024-05-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_dislike_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiontype',
            name='product_type',
            field=models.CharField(choices=[('GP', 'Gaming'), ('CP', 'Clothes'), ('SP', 'Shoes')], max_length=5),
        ),
    ]
