# Generated by Django 5.0.6 on 2024-05-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiontype',
            name='product_type',
            field=models.CharField(choices=[('EP', 'Electronics'), ('CP', 'Clothing'), ('SP', 'Shoes')], max_length=5),
        ),
    ]
